### ISSUE TITLE
Cannot retrieve Route Parameters

### ISSUE THREAD

**Issue by jeffmthomas** [awurth/slim-base#1]
I am having trouble getting the route parameters using this boilerplate.  Here is what I am doing:

Add to src/App/Resources/routes/app.php:
```
$app->get('/test/{testparam}', 'AppController:testParams')
    ->setName('test');
```

Add to src/App/Controller/AppController.php:
```
public function testParams($request, $response, $args) {
        echo $args['testparam'];
    }
```
Then go to: http://0.0.0.0:8888/test/thisistheparam and there you should see `thisistheparam` but instead there is an error and the first letter of the route parameter.

```
Warning: Illegal string offset 'testparam' in C:\Users\Jeff\Projects\test2\src\App\Controller\AppController.php on line 16
t
```

**Comment by awurth** [comment]
This is because I changed Slim's route strategies to get the params as separate arguments instead of an array.

If you want the old behaviour, just get rid these three lines at the end of `bootstrap/dependencies.php`:
```php
$container['foundHandler'] = function() {
    return new \Slim\Handlers\Strategies\RequestResponseArgs();
};
```

For more infos, check out the Slim documentation:
https://www.slimframework.com/docs/objects/router.html#route-strategies

**Comment by jeffmthomas** [comment]
Thanks, that was the solution.  I need to stop coding at 3am.
